services:
  mongo:
    image: mongo:8
    container_name: business-dashboard-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: business_dashboard

    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio
    container_name: business-dashboard-minio
    restart: unless-stopped

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

  api:
    build:
      context: ./api

    container_name: business-dashboard-api

    restart: unless-stopped

    depends_on:
      - mongo
      - minio

    env_file:
      - ./api/.env

    ports:
      - "3000:3000"

    command: npm run dev

    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  mongodb_data:
  minio_data:
