services:
  mongo:
    image: mongo:8
    container_name: business-dashboard-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: business_dashboard

    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: ./api

    container_name: business-dashboard-api

    restart: unless-stopped

    depends_on:
      - mongo

    env_file:
      - ./api/.env

    ports:
      - "3000:3000"

    command: npm run dev

    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  mongodb_data:
